### ISSUE TITLE
Update the way array mapping is done

### ISSUE THREAD

**Issue by nathanatrhea** [RHEAGROUP/DEH-ECOSIMPRO#95]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the DEHP-EcosimPro
- [x] I have searched [open](https://github.com/RHEAGROUP/DEHP-ECOSIMPRO/issues) and [closed](https://github.com/RHEAGROUP/DEHP-ECOSIMPRO/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Update the way array mapping is done
- Match the number of SFPT columns to the number of columns of the opc array. Still base on the number of rows
### System Configuration

- DEHPCommon version:
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by antoineatstariongroup** [comment]
Was fixed on PR #104
